In [2]:
import pandas as pd
fake=pd.read_csv("D://Study//Semester 5//ML-LAB\Final Project (Fake News Detection)//data//Fake.csv")
true=pd.read_csv("D://Study//Semester 5//ML-LAB\Final Project (Fake News Detection)//data//True.csv")
fake['label']=0
true['label']=1
df = pd.concat([fake, true]).sample(frac=1).reset_index(drop=True)
df.to_csv("D://Study//Semester 5//ML-LAB//Final Project (Fake News Detection)//data//combined_dataset.csv",index=False)
df.head()

,title,text,subject,date,label
0,Britain seeks new ways to detect explosives in...,LONDON (Reuters) - Britain launched a fund on ...,worldnews,"October 19, 2017",1
1,DEAR ANTI-TRUMP PROTESTERS: “Your Behavior Is ...,"You re carrying Mexican flags while chanting,...",left-news,"Nov 10, 2016",0
2,KARMA: GAY PASTOR SUES WHOLE FOODS For “Anti-G...,Too bad for the gay pastor that Whole Foods ha...,left-news,"Apr 20, 2016",0
3,HYSTERICAL! BERNIE SANDERS On Why ‘Very Popula...,Double standards everywhere! Socialist Bernie...,politics,"Nov 19, 2017",0
4,Kremlin says Putin ready to welcome any U.S. c...,MOSCOW (Reuters) - The Kremlin said on Wednesd...,politicsNews,"October 19, 2016",1

In [3]:
df

,title,text,subject,date,label
0,Britain seeks new ways to detect explosives in...,LONDON (Reuters) - Britain launched a fund on ...,worldnews,"October 19, 2017",1
1,DEAR ANTI-TRUMP PROTESTERS: “Your Behavior Is ...,"You re carrying Mexican flags while chanting,...",left-news,"Nov 10, 2016",0
2,KARMA: GAY PASTOR SUES WHOLE FOODS For “Anti-G...,Too bad for the gay pastor that Whole Foods ha...,left-news,"Apr 20, 2016",0
3,HYSTERICAL! BERNIE SANDERS On Why ‘Very Popula...,Double standards everywhere! Socialist Bernie...,politics,"Nov 19, 2017",0
4,Kremlin says Putin ready to welcome any U.S. c...,MOSCOW (Reuters) - The Kremlin said on Wednesd...,politicsNews,"October 19, 2016",1
...,...,...,...,...,...
44893,[VIDEO] CNN CO-ANCHOR CHRIS CUOMO’S OBVIOUS OB...,Where s the outcry from the left about the mis...,politics,"Jun 24, 2015",0
44894,INTERVIEW: Did the ‘Alt Right’ Die in Charlott...,The events in Charlottesville have shaken the ...,Middle-east,"August 15, 2017",0
44895,Ted Cruz Ends His Campaign By Elbowing His Wi...,"In case you haven t heard, God s chosen candid...",News,"May 3, 2016",0
44896,Slain Philippine teenager's family files murde...,MANILA (Reuters) - The parents and lawyers of ...,worldnews,"August 25, 2017",1
44897,THE TRUTH ABOUT WHY HILLARY Is The Only Candid...,This news should be enough to end Hillary s ob...,left-news,"Apr 27, 2016",0