In [18]:
from transformers import RobertaTokenizer, RobertaForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset
from sklearn.model_selection import train_test_split
import pandas as pd
df = pd.read_csv('/content/combined_dataset.csv')
train_texts,val_texts,train_labels,val_labels=train_test_split(df['text'].tolist(),df['label'].tolist(),test_size=0.2,random_state=42)
tokenizer=RobertaTokenizer.from_pretrained('roberta-base')
train_enc=tokenizer(train_texts,truncation=True,padding=True,max_length=512)
val_enc=tokenizer(val_texts,truncation=True,padding=True,max_length=512)
train_dataset=Dataset.from_dict({'input_ids':train_enc['input_ids'],'attention_mask':train_enc['attention_mask'],'labels':train_labels})
val_dataset=Dataset.from_dict({'input_ids':val_enc['input_ids'],'attention_mask': val_enc['attention_mask'],'labels': val_labels})
model=RobertaForSequenceClassification.from_pretrained('roberta-base', num_labels=2)
args=TrainingArguments(output_dir='/content/roberta_model',eval_strategy='epoch',per_device_train_batch_size=8,per_device_eval_batch_size=8,num_train_epochs=1,save_strategy='epoch',logging_strategy='epoch')
trainer=Trainer(model=model,args=args,train_dataset=train_dataset,eval_dataset=val_dataset)
trainer.train()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: subhanshahid1501 (subhanshahid1501-fast-nuces) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

TrainOutput(global_step=4490, training_loss=0.009121572413794979, metrics={'train_runtime': 3759.1992, 'train_samples_per_second': 9.555, 'train_steps_per_second': 1.194, 'total_flos': 9450422886420480.0, 'train_loss': 0.009121572413794979, 'epoch': 1.0})